### ISSUE TITLE
`count_touching_cells` is slow

### ISSUE THREAD

**Issue by PKI-Kent** [PerkinElmer/phenoptr#1]
`count_touching_cells` is slow; the culprit seems to be the call to `EBImage::floodFill` which returns a new image matrix for each call, leading to much garbage-collection. The `floodFill` itself seems to be reasonably fast.

See https://github.com/aoles/EBImage/issues/21 for a request to extend EBImage do include an in-place `floodFill`

**Comment by kent37** [comment]
Fixed with aacea141af45ac884c87a96f29eee201bddd298f and EBImage 4.19.9. Install the updated EBImage via
`devtools::install_github('aoles/EBImage')`
