### ISSUE TITLE
Phenoptr will not install

### ISSUE THREAD

**Issue by Athanasios72** [PerkinElmer/phenoptr#3]
I am trying to install the phenoptr package but it doesn't happen. See code below:
install.packages("devtools")
library(devtools)
install_github("PerkinElmer/phenoptr")
#output from last line...
> install_github("PerkinElmer/phenoptr")
**Installation failed: Couldn't connect to server**
Any help would be much appreciated...

**Comment by PKI-Kent** [comment]
Hi, sorry to reply so late! This sounds like a network issue. This ticket suggests it is a proxy issue:
https://github.com/lucasmation/microdadosBrasil/issues/138
and points to this ticket for some suggestions:
https://github.com/hadley/devtools/issues/877

**Comment by Athanasios72** [comment]
Thank you Kent! I solved the issue by installing the phenoptr package at home where there is no firewall. Thank you again.
