### ISSUE TITLE
count_touching_cells issue with writeTIFF

### ISSUE THREAD

**Issue by Athanasios72** [PerkinElmer/phenoptr#4]
Hi,

I am having an issue with the count_touching_cells function. I run the following code:
path <- "~/R ANALYSIS/T panel/5286/5286 tpan_[39110,12200]_cell_seg_data.txt"
pairs <- list(
  c('AE1AE3', 'CD3CD4'),
  c('AE1AE3', 'CD3CD8')
)
colors <- list('AE1AE3'='cyan', 'CD3CD4'='yellow', 'CD3CD8'='magenta')
count_touching_cells(path, pairs, colors, write_images = TRUE)

and get this output:
> count_touching_cells(path, pairs, colors, write_images = TRUE)
Error in writeTIFF(x, file, bits.per.sample = bits.per.sample, compression = compression,  : 
  unable to create ~/R ANALYSIS/T panel/5286/5286 pan_[39110,12200]_AE1AE3_touch_CD3CD4.tif

How can I solve this? Any help would be much appreciated.

Thank you.

**Comment by PKI-Kent** [comment]
This is an issue with `writeTiff`, see https://github.com/PerkinElmer/tiff/issues/1. To work around this, you can give a full path directly or call `path.expand` on your path, e.g.
`count_touching_cells(path.expand(path), pairs, colors, write_images = TRUE)`

If you are using the PerkinElmer fork of the `tiff` library, you can install a version which fixes this problem. See https://github.com/PerkinElmer/tiff for details.

**Comment by Athanasios72** [comment]
Thank you Kent! path.expand worked fine.
