### ISSUE TITLE
visualizing new phenotypes

### ISSUE THREAD

**Issue by haudi31** [PerkinElmer/phenoptr#5]
Is there already an option to count AND visualize[on image] double positives eg. Ck+ and PD-L1>5?
Counting I already do using new phenotype but if there is already a way to visualize it I will not do it by myself :)
Thanks a lot for the help!

**Comment by PKI-Kent** [comment]
@haudi31 Yes, the `spatial_distribution_report()` function allows specification of `phenotype_rules` which allow you to create double positive phenotypes such as your example. The documentation for the function has an example of exactly what you request - visualizing CK+ with PDL1>3.
https://perkinelmer.github.io/phenoptr/reference/spatial_distribution_report.html#examples

**Comment by haudi31** [comment]
Although i have "CK_PDL1" in phenotype_rules, ""CK_PDL1" with "cyan" in colors, "CK_PDL1" with "CD8" in "pairs" and `Entire Cell PD-L1 (Opal 540) Mean (Normalized Counts, Total Weighting)` in my cell_seq_path file i get an error message. What did i miss?

`phenotype_rules <- list(
    "CK_PDL1"=list("CK", ~`Entire Cell PD-L1 (Opal 540) Mean (Normalized Counts, Total Weighting)`>3))`

INPUT
spatial_distribution_report(paste0(getwd(),"/Daten/",temp[1]), pairs, colors,
                            phenotype_rules, output_path = paste0(getwd(),"/Daten/"),
                            pixels_per_micron = getOption("phenoptr.pixels.per.micron"))

OUTPUT:
```
processing file: SpatialDistributionReport.Rmd
  |....                                                             |   6%
   inline R code fragments

  |........                                                         |  12%
label: parameters (with options) 
List of 3
 $ echo   : logi FALSE
 $ include: logi FALSE
 $ message: logi FALSE

  |............                                                     |  19%
  ordinary text without R code

  |................                                                 |  25%
label: setup (with options) 
List of 3
 $ echo   : logi FALSE
 $ include: logi FALSE
 $ message: logi FALSE

  |....................                                             |  31%
   inline R code fragments

  |........................                                         |  38%
label: show_phenotypes (with options) 
List of 1
 $ results: chr "asis"

  |............................                                     |  44%
  ordinary text without R code

  |................................                                 |  50%
label: first_order_stats (with options) 
List of 1
 $ results: chr "asis"

Quitting from lines 98-110 (SpatialDistributionReport.Rmd) 
Error in eval(expr, data, expr_env) : 
  object 'Entire Cell PD-L1 (Opal 540) Mean (Normalized Counts, Total Weighting)' not found
```

**Comment by PKI-Kent** [comment]
You are so close...`spatial_distribution_report` uses `read_cell_seg_data` which helpfully (?) shortens the column names in the resulting `data_frame`, so they won't exactly match what is in your file. I think you need 
```
phenotype_rules <- list( "CK_PDL1"=list("CK", ~`Entire Cell PD-L1 (Opal 540) Mean`>3))
```
in your rules (and change the comparison value from `3` to what you want).

If you read your file with `read_cell_seg_data` and look at the names of the `data_frame` you can confirm the correct name.
